name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libboost-all-dev

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
